#!/usr/bin/env bash

# Switch the the root directory or bail
#PROJECT_ROOT=$(readlink -f $(dirname $BASH_SOURCE[0]))
#echo $PROJECT_ROOT
#cd "$PROJECT_ROOT" || exit 1

# Create the target name.enc.yaml file
DIR=$(dirname "$1")                 # get the diretory name
FILE_NAME=$(basename "$1")          # get the full file name
NAME="${FILE_NAME%%.*}"             # trim off the file extension
EXT="${FILE_NAME##*.}"              # trim off the prefix including the '.'
TARGET="$DIR/${NAME}.enc.${EXT}"

sops --encrypt "$1" > "$TARGET"
