#!/usr/bin/env bash

# --------------------------------------------------------------------------------------------------
# Install the indicated files to the system
# --------------------------------------------------------------------------------------------------
set -euo pipefail   # configure an immediate fail if something goes badly
files="$1"          # the /nix/store package with all the files that need installed

# Main entry point
# --------------------------------------------------------------------------------------------------
echo "installing files ${links}"
tree ${links}
