# devilspie2 configuration
#
# ### Description
# Window matching utility, the Lua based rewrite of the original `devilspie`. It runs as a small
# per-session daemon that listens for window events over libwnck and executes Lua scripts against
# matching windows i.e. move/resize, pin, set workspace, always on top, undecorate.
#
# - Costs almost nothing: the package itself is ~92 KiB and every dependency (GTK3, GLib, Lua,
#   libwnck) is already in the XFCE closure. Idle CPU is zero as it is purely event driven.
# - X11 only. libwnck talks EWMH over X11, so this cannot see or move native Wayland windows. Hence
#   the `system.x11.enable` assertion below. Under Plasma/Wayland use KWin's own window rules.
#
# ### Configuration
# - `scripts` entries are installed as `~/.config/devilspie2/<name>.lua` and run on window open
# - `on.<event>` lists promote scripts to other events via the generated `devilspie2.lua` index; a
#   script named in one of those lists is no longer run on window open
# - devilspie2 watches the script folder and reloads automatically when its content changes
# - devilspie2 exits immediately when the script folder is empty, so the autostart entry is only
#   installed once at least one script is defined
#
# ### Other notes
# - Some apps set their own geometry after mapping and will race the rule. Applying the geometry a
#   second time in the same script is the usual workaround.
# - `debug = true` is what makes `debug_print` output visible, which lands in the session log
# --------------------------------------------------------------------------------------------------
{ config, lib, pkgs, ... }: with lib.types;
let
  cfg = config.apps.system.devilspie2;

  # Lua list literal of script filenames for the devilspie2.lua index
  luaList = names: "{ " + (lib.concatMapStringsSep ", " (x: "\"${x}.lua\"") names) + " }";

  events = {
    windowClose = "scripts_window_close";
    windowFocus = "scripts_window_focus";
    windowBlur = "scripts_window_blur";
    windowNameChange = "scripts_window_name_change";
  };

  # devilspie2's own index file, mapping scripts to events other than window open. Only written when
  # at least one event actually has scripts assigned to it.
  indexFile = lib.concatStringsSep "\n" ([
    "-- Generated by modules/apps/system/devilspie2 - do not edit"
  ] ++ (lib.mapAttrsToList (opt: global: "${global} = ${luaList cfg.on.${opt}}")
    (lib.filterAttrs (opt: _: cfg.on.${opt} != [ ]) events))) + "\n";

  anyEvents = lib.any (x: x != [ ]) (lib.attrValues cfg.on);

  eventScriptOption = event: lib.mkOption {
    description = lib.mdDoc "Names of `scripts` entries to run on the ${event} event instead of on window open";
    type = types.listOf types.str;
    default = [ ];
    example = [ "terminal" ];
  };
in
{
  options = {
    apps.system.devilspie2 = {
      enable = lib.mkEnableOption "Install and configure devilspie2 window matching";

      autostart = lib.mkOption {
        description = lib.mdDoc "Autostart devilspie2 after login, when any scripts are configured";
        type = types.bool;
        default = true;
      };

      debug = lib.mkOption {
        description = lib.mdDoc "Run with `--debug` so `debug_print` calls in scripts are printed";
        type = types.bool;
        default = false;
      };

      emulate = lib.mkOption {
        description = lib.mdDoc ''
          Run with `--emulate` so scripts can read window state and print, but never actually change
          a window. Useful with `debug` for working out the class/name of a window to match on.
        '';
        type = types.bool;
        default = false;
      };

      scripts = lib.mkOption {
        description = lib.mdDoc "Lua scripts to install, keyed by name without the `.lua` suffix";
        type = types.attrsOf types.lines;
        default = { };
        example = lib.literalExpression ''
          {
            pin-messaging = '''
              if (get_window_class() == "Signal") then
                set_window_workspace(2);
                pin_window();
              end
            ''';
          }
        '';
      };

      on = {
        windowClose = eventScriptOption "window close";
        windowFocus = eventScriptOption "window focus";
        windowBlur = eventScriptOption "window blur";
        windowNameChange = eventScriptOption "window name change";
      };
    };
  };

  config = lib.mkIf (cfg.enable) (lib.mkMerge [
    {
      assertions = [
        {
          assertion = config.system.x11.enable;
          message = "apps.system.devilspie2 requires system.x11.enable, libwnck cannot drive native Wayland windows.";
        }
        {
          assertion = lib.all (x: cfg.scripts ? ${x}) (lib.concatLists (lib.attrValues cfg.on));
          message = "apps.system.devilspie2.on.* references a script not defined in apps.system.devilspie2.scripts.";
        }
      ];

      environment.systemPackages = [ pkgs.devilspie2 ];
    }

    # Install the scripts and, when needed, devilspie2's event index
    {
      files.all = (lib.mapAttrs' (name: text:
        lib.nameValuePair ".config/devilspie2/${name}.lua" { copy = text; }
      ) cfg.scripts) // lib.optionalAttrs (anyEvents) {
        ".config/devilspie2/devilspie2.lua".copy = indexFile;
      };
    }

    # Autostart after login. Skipped without scripts as devilspie2 exits on an empty script folder.
    (lib.mkIf (cfg.autostart && cfg.scripts != { }) {
      environment.etc."xdg/autostart/devilspie2.desktop".text = ''
        [Desktop Entry]
        Type=Application
        Name=Devilspie2
        Terminal=false
        Exec=${pkgs.devilspie2}/bin/devilspie2${lib.optionalString cfg.debug " --debug"}${lib.optionalString cfg.emulate " --emulate"}
      '';
    })
  ]);
}
