add_newline = false
command_timeout = 10000
palette = "cyber"

format = """
$container\
$username\
${custom.user_hostname}\
${custom.root_hostname}\
${custom.user_arrow}\
${custom.root_arrow}\
$directory\
[](fg:color_light_gray bg:color_dark_blue)\
$git_branch\
$git_status\
[ ](fg:color_dark_blue)\
"""

[palettes.cyber]
color_light_gray = "#606365"
color_light_blue = "#0488D3"
color_dark_blue = "#1c638d"
color_light_red = "#d31f04"
color_white = "#ffffff"

[container]
style = "bg:#0488D3"
format = '[ $name ]($style)'

[username]
style_user = "fg:color_white bg:color_light_blue"
style_root = "fg:color_white bg:color_light_red"
format = "[ $user]($style)"
show_always = true
disabled = false

[custom.user_hostname]
command = "uname -n"
when = '''test "$USER" != "root"'''
format = "[@$output ](fg:color_white bg:color_light_blue)"

[custom.root_hostname]
when = '''test "$USER" = "root"'''
format = "[@$output ](fg:color_white bg:color_light_red)"

[custom.user_arrow]
when = '''test "$USER" != "root"'''
format = "[](fg:color_light_blue bg:color_light_gray)"

[custom.root_arrow]
when = '''test "$USER" = "root"'''
format = "[](fg:color_light_red bg:color_light_gray)"

[directory]
format = "[ $path ](fg:color_white bg:color_light_gray)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
symbol = ""
format = '[ $symbol $branch ](fg:color_white bg:color_dark_blue)'

[git_status]
ahead = '⇡ ${count}'
behind = '⇣ ${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = '[$all_status$ahead_behind ](fg:color_white bg:color_dark_blue)'
