# Example:
# https://github.com/mickimnet/myth-prompt-themes/blob/main/colorful/pointed/starship/left_only/starship.toml
[palettes.cyber]
color_light_gray = "#606365"
color_light_blue = "#0488D3"
color_dark_blue = "#1c638d"
color_light_red = "#d31f04"

format = """
$container\
$hostname\
$username\
${custom.user_arrow}\
${custom.root_arrow}\
$directory\
[](fg:color_light_gray bg:color_dark_blue)\
$git_branch\
$git_status\
[ ](fg:color_dark_blue)\
"""

add_newline = false
command_timeout = 10000
palette = "cyber"

[container]
style = "bg:#0488D3"
format = '[ $name ]($style)'

[hostname]
ssh_only = true
style = "bg:#0488D3"
format = "[ @$hostname ]($style)"
trim_at = "."
disabled = false

[username]
style_user = "bg:color_light_blue"
style_root = "bg:color_light_red"
format = "[ $user ]($style)"
show_always = true
disabled = false

[custom.user_arrow]
when = '''test "$USER" != "root"'''
format = "[](fg:color_light_blue bg:color_light_gray)"

[custom.root_arrow]
when = '''test "$USER" = "root"'''
format = "[](fg:color_light_red bg:color_light_gray)"

[directory]
format = "[ $path ](bg:color_light_gray)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
symbol = ""
format = '[ $symbol $branch ](bg:color_dark_blue)'

[git_status]
ahead = '⇡ ${count}'
behind = '⇣ ${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = '[$all_status$ahead_behind ](bg:color_dark_blue)'
