# Example
# https://github.com/mickimnet/myth-prompt-themes/blob/main/colorful/pointed/starship/left_only/starship.toml
add_newline = false
command_timeout = 10000
palette = "cyber"

format = """
$container\
${custom.user_name}\
${custom.user_root}\
${custom.user_ssh}\
${custom.hostname_user}\
${custom.hostname_root}\
${custom.hostname_ssh}\
${custom.arrow_user}\
${custom.arrow_root}\
${custom.arrow_ssh}\
$directory\
[](fg:color_light_gray bg:color_dark_blue)\
$git_branch\
$git_status\
[ ](fg:color_dark_blue)\
"""

[palettes.cyber]
color_light_gray = "#606365"
color_light_blue = "#0488D3"
color_dark_blue = "#1c638d"
color_light_red = "#d31f04"
color_light_orange = "#ff7b00"
color_white = "#ffffff"

[container]
style = "bg:#0488D3"
format = '[ $name ]($style)'

# Non ssh user and not root
[custom.user_name]
command = "echo $USER"
when = '[[ ! -n "$SSH_CONNECTION" && "$USER" != "root" ]]'
shell = ["bash", "--noprofile", "--norc"]
format = "[ $output](fg:color_white bg:color_light_blue)"

# Non ssh user and root
[custom.user_root]
when = '[[ ! -n "$SSH_CONNECTION" && "$USER" == "root" ]]'
shell = ["bash", "--noprofile", "--norc"]
format = "[ root](fg:color_white bg:color_light_red)"

# Any ssh user
[custom.user_ssh]
command = "echo $USER"
when = '[[ -n "$SSH_CONNECTION" ]]'
shell = ["bash", "--noprofile", "--norc"]
format = "[ $output](fg:color_white bg:color_light_orange)"

[custom.hostname_user]
command = "uname -n"
when = '[[ ! -n "$SSH_CONNECTION" && "$USER" != "root" ]]'
shell = ["bash", "--noprofile", "--norc"]
format = "[@$output ](fg:color_white bg:color_light_blue)"

[custom.hostname_root]
command = "uname -n"
when = '[[ ! -n "$SSH_CONNECTION" && "$USER" == "root" ]]'
shell = ["bash", "--noprofile", "--norc"]
format = "[@$output ](fg:color_white bg:color_light_red)"

[custom.hostname_ssh]
command = "uname -n"
when = '[[ -n "$SSH_CONNECTION" ]]'
shell = ["bash", "--noprofile", "--norc"]
format = "[@$output ](fg:color_white bg:color_light_orange)"

[custom.arrow_user]
when = '[[ ! -n "$SSH_CONNECTION" && "$USER" != "root" ]]'
shell = ["bash", "--noprofile", "--norc"]
format = "[](fg:color_light_blue bg:color_light_gray)"

[custom.arrow_root]
when = '[[ ! -n "$SSH_CONNECTION" && "$USER" == "root" ]]'
shell = ["bash", "--noprofile", "--norc"]
format = "[](fg:color_light_red bg:color_light_gray)"

[custom.arrow_ssh]
when = '[[ -n "$SSH_CONNECTION" ]]'
shell = ["bash", "--noprofile", "--norc"]
format = "[](fg:color_light_orange bg:color_light_gray)"

[directory]
format = "[ $path ](fg:color_white bg:color_light_gray)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
symbol = ""
format = '[ $symbol $branch ](fg:color_white bg:color_dark_blue)'

[git_status]
ahead = '⇡ ${count}'
behind = '⇣ ${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = '[$all_status$ahead_behind ](fg:color_white bg:color_dark_blue)'
