format = """
$container\
$username\
$hostname\
$directory\
[](fg:#606365 bg:#1c638d)\
$git_branch\
$git_status\
[ ](fg:#1c638d)\
"""
#[](fg:#0488D3 bg:#606365)\

add_newline = false
command_timeout = 10000

[container]
style = "bg:#0488D3 fg:#FFFFFF"
format = '[ $name ]($style)'

[username]
# cyber blue background for user
style_user = "bg:#0488D3 fg:#FFFFFF"
# red background for root user
style_root = "bg:#d31f04 fg:#FFFFFF"
format = '[ $user ]($style)'
show_always = true
disabled = false

[hostname]
ssh_only = true
style = "bg:#0488D3 fg:#FFFFFF"
format = "[@$hostname]($style)"
trim_at = "."
disabled = false

[directory]
style = "fg:#FFFFFF bg:#606365"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
symbol = ""
style = "bg:#1c638d"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#1c638d"
ahead = '⇡ ${count}'
behind = '⇣ ${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = '[$all_status$ahead_behind ]($style)'
