#!/usr/bin/env bash

# Import core functions
source "${SCRIPT_DIR}/lib/build"
source "${SCRIPT_DIR}/lib/clean"
source "${SCRIPT_DIR}/lib/install"
source "${SCRIPT_DIR}/lib/logs"
source "${SCRIPT_DIR}/lib/manage"
source "${SCRIPT_DIR}/lib/pkgs/pkgs"
source "${SCRIPT_DIR}/lib/update"

# Import utilities
source "${SCRIPT_DIR}/lib/log"
source "${SCRIPT_DIR}/lib/utils"
