#!/usr/bin/env bash

# Import sub commands
source "${SCRIPT_DIR}/lib/init"
source "${SCRIPT_DIR}/lib/build"
source "${SCRIPT_DIR}/lib/clean/clean"
source "${SCRIPT_DIR}/lib/dev"
source "${SCRIPT_DIR}/lib/deploy"
source "${SCRIPT_DIR}/lib/flake"
source "${SCRIPT_DIR}/lib/install"
source "${SCRIPT_DIR}/lib/list"
source "${SCRIPT_DIR}/lib/logs"
source "${SCRIPT_DIR}/lib/manage"
source "${SCRIPT_DIR}/lib/pkgs/pkgs"
source "${SCRIPT_DIR}/lib/registry"
source "${SCRIPT_DIR}/lib/run"
source "${SCRIPT_DIR}/lib/shell"
source "${SCRIPT_DIR}/lib/switch"
source "${SCRIPT_DIR}/lib/test"
source "${SCRIPT_DIR}/lib/update"
source "${SCRIPT_DIR}/lib/upgrade"

# Import utility functions
source "${SCRIPT_DIR}/lib/log"
source "${SCRIPT_DIR}/lib/utils"
