#!/usr/bin/env bash
#set -x

# Build code
# 
# ## Features
# * The ISO build target is 'develop' by default which is the heaviest profile and builds on all the 
# other profiles which means that all packages will be included on the ISO. By changing the ISO 
# target to something smaller like 'light' we can create a smaller ISO with less packages included.
#
# --------------------------------------------------------------------------------------------------

# Usage for the build command and its sub commands
# --------------------------------------------------------------------------------------------------
build::usage()
{
    cat <<USAGE
Usage:
  build [COMMAND] [ARGS...] [OPTIONS] 

Options:
  -h, --help                Print out usage
  --vm.service=VALUE        Configure VM as systemd service (default=false) [true|false]
  --vm.hostname=VALUE       Configure VM hostname also used as systemd unit name (default=nixos)
  --vm.ip=VALUE             IP Address to use for the VM
  --vm.spice=VALUE          Use SPICE for this VM (default=false) [true|false]
  --vm.spicePort=VALUE      SPICE port to use (default=5901)
  --vm.cores=VALUE          Cores to use (default=4)
  --vm.diskSize=VALUE       Disk size in GiB to use (default=20)
  --vm.memorySize=VALUE     Memory size in GiB to use (default=4)
  --vm.resolution.x=VALUE   Y Resolution value to use (default=1920)
  --vm.resolution.y=VALUE   Y Resolution value to use (default=1080)
  --no-clean                Don't clean up the args file afterward

Commands:
  iso [PROFILE]             Build the installable ISO with an optional profile override
  vm [PROFILE]              Build the VM with an optional profile override
USAGE

    log::ln "\nExamples:"
    log::subln "Build the VM: ${green}./${SCRIPT} build vm${none}"
    log::subln "Build spice VM: ${green}./${SCRIPT} build vm generic/server --vm.service=true --vm.hostname=nixos71 --vm.ip=192.168.1.71/24 --vm.spice=true --vm.spicePort=5971 --vm.diskSize=2${none}"
    log::subln "Build the installable ISO: ${green}./${SCRIPT} build iso${none}"
    log::subln "Build the installable ISO: ${green}./${SCRIPT} build iso generic/light${none}"
    echo
    exit
}

# Parse the build commands and execute
# --------------------------------------------------------------------------------------------------
build::run()
{
    utils::help "$@" "build::usage"

    local command=$1; shift
    case "$command" in
        iso) build::iso "$@" ;;
        vm) build::vm "$@" ;;
        *) log::error "Invalid build command: ${cyan}${command}${none}"; echo; build::usage ;;
    esac
}
 
# Build the installable iso
# --------------------------------------------------------------------------------------------------
# https://releases.nixos.org/
# https://discourse.nixos.org/t/nixos-reproducible-builds-minimal-installation-iso-successfully-independently-rebuilt/34756
# --------------------------------------------------------------------------------------------------
build::iso()
{
    core::title
    log::header0 "Building installable ISO"

    local profile="$1"
    if [[ "$profile" != "" ]]; then
        profile="${profile%.*}" # trim off the file extension
        _build::update_flake_args "$FLAKE_ISO_ARGS" "str" "profile" "$profile"
    fi

    nix build .#nixosConfigurations.iso.config.system.build.isoImage

    [[ "$profile" != "" ]] && _build::restore_flake_args
}

# Build the vm
# --------------------------------------------------------------------------------------------------
build::vm()
{
    NO_CLEAN="${NO_CLEAN:-0}"

    local service="false"
    local hostname="nixos"
    local args="$FLAKE_VM_ARGS"

    core::title
    log::header0 "Building VM"

    # Set arg overrides as directed
    while [ $# -gt 0 ]; do
        local arg=$1; shift
        case "$arg" in
            --vm.hostname*)
                _build::update_flake_args "$args" "str" "hostname" "$arg" true
                hostname="${arg#*=}" # trim the prefix including the '='
                ;;
            --vm.service*)
                _build::update_flake_args "$args" "bool" "vm.service" "$arg" true
                service="${arg#*=}" # trim the prefix including the '='
                ;;
            --vm.ip*) _build::update_flake_args "$args" "str" "static_ip" "$arg" true ;;
            --vm.spicePort*) _build::update_flake_args "$args" "int" "vm.spicePort" "$arg" true ;;
            --vm.spice*) _build::update_flake_args "$args" "bool" "vm.spice" "$arg" true ;;
            --vm.cores*) _build::update_flake_args "$args" "int" "vm.cores" "$arg" true ;;
            --vm.diskSize*) _build::update_flake_args "$args" "int" "vm.diskSize" "$arg" true ;;
            --vm.memorySize*) _build::update_flake_args "$args" "int" "vm.memorySize" "$arg" true ;;
            --vm.resolution.x*) _build::update_flake_args "$args" "int" "vm.resolution.x" "$arg" true ;;
            --vm.resolution.y*) _build::update_flake_args "$args" "int" "vm.resolution.y" "$arg" true ;;
            --no-clean) NO_CLEAN=1 ;;
            --*) log::error "Invalid vm argument: ${cyan}${arg}${none}"; echo; build::usage ;;
            *) _build::update_flake_args "$args" "str" "profile" "$arg" ;;
        esac
    done

    nix build .#nixosConfigurations.vm.config.system.build.vm

    # Move the service files 
    if [[ "${hostname}" == "true" ]]; then
        mkdir -p "/var/lib/vm-${hostname}"
        mv "$SCRIPT_DIR/result" "/var/lib/vm-${hostname}/"
    fi

    _build::restore_flake_args
}

# Change the given variable in the flake args file
# $1 - target args file
# $2 - the kind of value [str|bool|int]
# $3 - the name of the variable to change in the args file e.g. flake_private.nix
# $4 - the value to set
# $5 - the value is a name=value pair
_build::update_flake_args()
{
    local args="$1"
    local kind="$2"
    local var="$3"
    local value="$4"
    local pair="$5"

    # Create the args file if necessary
    if [ ! -f "$args" ]; then
        cp "$FLAKE_ARGS" "$args"
    fi

    # Parse out the value from the pair
    if [[ "$pair" == "true" ]]; then
        value="${value#*=}"     # trim the prefix including the '='
    fi

    log::ln "Updating flake args ${args}: ${cyan}${var}${none} => ${cyan}${value}${none}"
    utils::replace "${kind}" "${var}" "${value}" "$args" 
    git add "${args}" -f

    # Switch out the flake args target ./flake_private.nix with
    # ./flake_vm_args.nix or ./flake_iso_args.nix depending
    local from=$(basename ${FLAKE_ARGS})
    local to=$(basename ${args})
    sed -i -e "s|\(^.*\)${from}\(.*$\)|\1${to}\2|" "${FLAKE}"
    git add "${FLAKE}"

    # Ensure the flake args are reset
    trap _build::cleanup INT KILL
}

# Restore the flake args back to what is was before
_build::restore_flake_args()
{
    [ $NO_CLEAN -eq 1 ] && return

    if [[ "$(git diff --staged --name-only -- ${FLAKE})" != "" ]]; then
        log::ln "Restoring flake args back to original"
        git restore --staged "${FLAKE}"
        git checkout "${FLAKE}"
    fi

    # Restore the temp args file as well
    if [[ "$(git diff --staged --name-only -- ${FLAKE_VM_ARGS})" != "" ]]; then
        git restore --staged "${FLAKE_VM_ARGS}"
        rm -f "${FLAKE_VM_ARGS}"
    fi
    if [[ "$(git diff --staged --name-only -- ${FLAKE_ISO_ARGS})" != "" ]]; then
        git restore --staged "${FLAKE_ISO_ARGS}"
        rm -f "${FLAKE_ISO_ARGS}"
    fi
}

# Cleanup if interrupted or failed after changing variables
_build::cleanup()
{
    _build::restore_flake_args
    exit 0
}
