#!/usr/bin/env bash

# Build code
# 
# ## Features
#
# --------------------------------------------------------------------------------------------------

# Usage for the build command and its sub commands
# --------------------------------------------------------------------------------------------------
build::usage()
{
    cat <<USAGE
Usage:
  build [OPTIONS] [COMMAND] [ARGS...]

Options:
  -h, --help        Print out usage

Commands:
  iso               Build the installable ISO
  vm                Build the test VM
USAGE

    log::ln "\nExamples:"
    log::subln "Build the test VM: ${green}./${SCRIPT} build vm${none}"
    log::subln "Build the installable ISO: ${green}./${SCRIPT} build iso${none}"
    echo
    exit
}


# Parse the build commands and execute
# --------------------------------------------------------------------------------------------------
build::run()
{
    utils::help "$@" "build::usage"

    local command=$1; shift
    case "$command" in
        iso) build::iso "$@" ;;
        vm) build::vm "$@" ;;
        *) log::error "Invalid build command: ${cyan}${command}${none}"; build::usage ;;
    esac
}
 
# Build the installable iso
# --------------------------------------------------------------------------------------------------
# https://releases.nixos.org/
# https://discourse.nixos.org/t/nixos-reproducible-builds-minimal-installation-iso-successfully-independently-rebuilt/34756
# --------------------------------------------------------------------------------------------------
build::iso()
{
    core::title
    log::header0 "Building installable ISO"
    nix build .#nixosConfigurations.iso.config.system.build.isoImage
}

# Build the test vm
# --------------------------------------------------------------------------------------------------
build::vm()
{
    core::title
    log::header0 "Building test VM"
    nix build .#nixosConfigurations.vm.config.system.build.vm
}
