#!/usr/bin/env bash

# Usage for the clean command and its sub commands
# --------------------------------------------------------------------------------------------------
clean::usage()
{
    cat <<USAGE
Usage:
  clean [OPTIONS] [COMMAND] [ARGS...]

Options:
  -h, --help        Print out top level usage

Commands:
  all               Clean everything
  store             Clean the nix store
USAGE

    log::ln "\nExamples:"
    log::subln "Clean nix store: ${green}./${SCRIPT} clean all${none}"
    log::subln "Clean nix store: ${green}./${SCRIPT} clean store${none}"
    echo
    exit
}


# Parse the clean commands and execute
# --------------------------------------------------------------------------------------------------
clean::run()
{
    [[ $# -eq 0 || $1 == "-h" || $1 == "--help" ]] && clean::usage

    # Parse the clean commnand
    local command=$1; shift
    case "$command" in
        all) clean::store -d ;;
        store) clean::store ;;
        *) log::error "Invalid clean command: ${cyan}${command}${none}"; clean::usage ;;
    esac
}

# Clean up nix store
# --------------------------------------------------------------------------------------------------
clean::store()
{
    # First clean up all older generations
    [[ $1 == "-d" ]] && nix-collect-garbage -d

    # Now clean the nix store
    nix-store --gc
}
