#!/usr/bin/env bash
#set -x

# Decrypt encrypted files in project
# --------------------------------------------------------------------------------------------------

# Usage for the decrypt command and its sub commands
# --------------------------------------------------------------------------------------------------
decrypt::usage()
{
    cat <<USAGE
Usage:
  decrypt [COMMAND] [ARGS...] [OPTIONS] 

Options:
  -h, --help            Print out usage
USAGE

    log::ln "\nExamples:"
    log::subln "Decrypt files: ${green}./${SCRIPT} decrypt${none}"
    log::subln "Clean decrypted files: ${green}./${SCRIPT} clean dec${none}"
    echo
    exit
}

# Parse the decrypt commands and execute
# --------------------------------------------------------------------------------------------------
decrypt::run()
{
  utils::decrypt "$CONFIG_DIR"

  # To clean decrypted files
  # ./clu clean dec
}
