#!/usr/bin/env bash
#set -x

# Deploy Virtual Machine
# 
# ## Features
# -
# --------------------------------------------------------------------------------------------------

# Usage for the deploy command and its sub commands
# --------------------------------------------------------------------------------------------------
deploy::usage()
{
    cat <<USAGE
Usage:
  deploy [COMMAND] [ARGS...] [OPTIONS] 

Options:
  -h, --help            Print out usage

Commands:
  vm HOST               Deploy the given VM host
USAGE

    log::ln "\nExamples:"
    log::subln "Deploy prod1 VM: ${green}./${SCRIPT} deploy vm prod1${none}"
    echo
    exit
}

# Parse the deploy commands and execute
# --------------------------------------------------------------------------------------------------
deploy::run()
{
    utils::help "$@" "deploy::usage"

    local command=$1; shift
    case "$command" in
        vm) deploy::vm "$@" ;;
        *) log::error "Invalid deploy command: ${cyan}${command}${none}"; echo; deploy::usage ;;
    esac
}
 
# Deploy the vm to the host at /var/lib/vms/$HOST
# - $1 - optional host name to target
# --------------------------------------------------------------------------------------------------
deploy::vm()
{
    core::preamble

    # Ensure host is set
    HOST="vm-${1#vm-}" # ensure 'vm-' prefix
    log::header1 "Deploying ${cyan}${HOST}${none}"

    # Target includes the prefix path
    TARGET="hosts/${HOST}"
    flake::ensure_target "$HOST"

    local host_dst="/var/lib/vms/$HOST"

    # Remove any existing
    log::ls -n "Cleaning target directory ${cyan}${host_dst}${none}..."
    utils::confirm_continue
    rm -rf "${host_dst}"

    # Copy over latest
    log::ls -n "Creating destination directories ${cyan}${host_dst}${none}..."
    mkdir -p "${host_dst}"
    log::status

    log::ls -n "Copying source to ${cyan}${host_dst}${none}..."
    cp -r ${CONFIG_DIR}/. "$host_dst"
    log::status

    # Build the deployed vm
    log::ls "Switching to ${cyan}${host_dst}${none} to build VM"
    pushd "$host_dst"
    ./clu build vm $HOST
    popd
}
