#!/usr/bin/env bash
#set -x

# Initialize clu and or the nixos-config flake repo
# 
# ## Features
# - setting up git hooks so decrypt secrets locally on git events
# --------------------------------------------------------------------------------------------------

# Usage for the init command and its sub commands
# --------------------------------------------------------------------------------------------------
init::usage()
{
    cat <<USAGE
Usage:
  init [COMMAND] [ARGS...] [OPTIONS] 

Options:
  -h, --help            Print out usage

USAGE

    log::ln "\nExamples:"
    log::subln "Init: ${green}./${SCRIPT} init${none}"
    echo
    exit
}

# Parse the init commands and execute
# --------------------------------------------------------------------------------------------------
init::run()
{
    utils::help "$@" zero "init::usage"

    core::preamble
    log::header0 "Initializing repo ${cyan}${CONFIG_DIR}${none}"

    # Prompt user to copy SOPS keys from existing machine for new system
    if [[ ! -d ~/.config/sops ]]; then
        utils::read SCP_SOPS 'Do you want to copy sops keys from an existing machine' 'n'
        if [[ "x${SCP_SOPS}" == "xy" ]]; then
            utils::read SCP_HANDLE 'Enter the scp target i.e. user@ip-address'
            if [[ "x${SCP_HANDLE}" != "x" ]]; then
                utils::get_user
                local config_dir="/home/$USER/.config"

                log::ls -n "SCP SOPS keys to user .config/..."
                scp -r ${SCP_HANDLE}:~/.config/sops "$config_dir"
                log::status

                log::ls -n "Copy SOPS keys to root .config/ as well..."
                sudo cp -r "${config_dir}/sops" /root/.config/
                log::status
            fi
        fi
    fi

    utils::run pushd "${CONFIG_DIR}"

    if [[ "$(git remote -v)" != *"phR0ze/nixos-config"* ]]; then
        log::ls -n "Stash current changes to the repo..."
        utils::run sudo git stash
        log::status

        log::ls -n "Add remote ${cyan}https://github.com/phR0ze/nixos-config${none}..."
        utils::run sudo git remote add origin https://github.com/phR0ze/nixos-config
        log::status

        log::ls -n "Fetch latest from the remote..."
        utils::run sudo git fetch
        log::status

        log::ls -n "Setup branch tracking for ${cyan}origin/main${none}..."
        utils::run sudo git branch -u origin/main
        log::status

        log::ls -n "Reset hard on ${cyan}origin/main${none}..."
        utils::run sudo git reset --hard origin/main
        log::status

        log::ls -n "Pop the stashed changes..."
        utils::run sudo git stash pop
        log::status
    fi

    log::ls -n "Configuring core.hooksPath: ${cyan}.githooks${none}..."
    utils::run sudo git config --local core.hooksPath .githooks
    log::status

    log::ls -n "Configuring decrypt alias: ${cyan}git decrypt${none}..."
    utils::run sudo git config --local alias.decrypt '!decrypt() { .githooks/decrypt; }; decrypt'
    log::status

    # Optionally encrypt the temp install args file
    local machine="machines/$(hostname)"
    local install_dec="${machine}/args.dec.json"
    if [[ "$(git diff --staged --name-only -- ${install_dec})" != "" ]]; then
        local install_enc="${machine}/args.enc.json"
        local root_uuid="$(cat $install_dec | jq -r '.drives[0].uuid')"
        local hardware="${machine}/hardware-configuration.nix"
        if [[ "$(grep ${root_uuid} ${hardware})" != "" ]]; then
            log::ls -n "Updating ${cyan}${hardware}${none} with drive uuid variable"
            utils::run sudo sed -i "s/${root_uuid}/\${(builtins.elemAt config.machine.drives 0).uuid}/g" $hardware
            log::status
        fi
        log::ls -n "Encrypting ${cyan}${install_dec}${none} to ${cyan}${install_enc}${none}"
        sudo sops --encrypt $install_dec > $install_enc
        log::status
    fi

    utils::run popd
}
