#!/usr/bin/env bash

# Logging code
# 
# ## Features
#
# --------------------------------------------------------------------------------------------------
none="\e[m"
red="\e[1;31m"
cyan="\e[1;36m"
green="\e[1;32m"
yellow="\e[1;33m"

# Print out a header
# --------------------------------------------------------------------------------------------------
# ### Params
# - $1 char to use for the separation line
# - $2 color to use
# - $3 header message
# - $4 double header or not 1/0
log::header()
{
    local char=$1
    local color=$2
    local msg=$3
    local double=$4

    # If the message has no color then colorize it
    [[ "${msg}" != *"\e[1"* ]] && msg="${color}${msg}${none}"

    echo
    [ "x$double" == "x1" ] && echo -e ${color}$_{1..80}'\b'"${char}"${none}
    echo -e ":: ${msg}"
    echo -e ${color}$_{1..80}'\b'"${char}"${none}
}

# Dump out debug variables
log::vars()
{
    log::d ">> Debug variables"
}

# Takes the value in $1 and prints it out if in debug mode
log::d()
{
    local msg=$1

    if [ "x${DEBUG}" == "x1" ]; then
        echo -e "${yellow}$msg${none}"
    fi
}

# vim: ft=sh:ts=4:sw=4:sts=4
