#!/usr/bin/env bash

# Package management commands
# 
# ## Features
#
# --------------------------------------------------------------------------------------------------

# Usage for the pkgs command and its sub commands
# --------------------------------------------------------------------------------------------------
pkgs::usage()
{
  cat <<USAGE
Usage:
  pkgs [options] [COMMAND] [ARGS...]

Options:
  -h, --help        Print out top level usage

Commands:
  ll                List different packge details (newline delimited)
  ls                List different packge details (space delimited)
USAGE

    log::ln "\nExamples:"
    log::subln "List binary's package: ${green}./${SCRIPT} pkgs ll pkg dircolors${none}"
    echo
    exit
}


# Parse the pkgs commands and execute
# --------------------------------------------------------------------------------------------------
pkgs::run()
{
    # Handle arguments
    [[ $# -eq 0 || $1 == "-h" || $1 == "--help" ]] && pkgs::usage

    # Parse the pkgs commnand
    local command=$1; shift
    case "$command" in
        ll) pkgs::list "ll" $@ ;;
        ls) pkgs::list "ls" $@ ;;
        *) log::error "Invalid pkgs command: ${cyan}${command}${none}"; pkgs::usage ;;
    esac
}

# Usage specific to the list sub-command
# --------------------------------------------------------------------------------------------------
list::usage()
{
    cat <<USAGE
Usage:
  ll [options] [COMMAND] [ARGS...]

Options:
  -h, --help        Print out top level usage

Commands:
  pkg BINARY        List detail about the package the target belongs to
USAGE

    log::ln "\nExamples:"
    log::subln "List binary's package: ${green}./${SCRIPT} pkgs ll pkg dircolors${none}"
    echo
    exit
}


# Parse list sub commands
# --------------------------------------------------------------------------------------------------
pkgs::list()
{
    local cmd="$1"; shift
    #[ "$cmd" == "ls" ] && echo space
    #[ "$cmd" == "ll" ] && echo newline
    [[ $# -eq 0 || $1 == "-h" || $1 == "--help" ]] && list::usage

    local command=$1; shift
    case "$command" in
        pkg) list::pkg "$@" ;;
        *) log::error "Invalid pkgs command: ${cyan}${command}${none}"; list::usage ;;
    esac
}

# List out the package the binary belongs to
# - binary needs to be findable with 'which'
#
# ### Args
# - $1 is the target to lookup
# --------------------------------------------------------------------------------------------------
list::pkg()
{
    [[ $# -eq 0 || $1 == "-h" || $1 == "--help" ]] && list::usage

    local target="$1"
    local bin_path=$(which "$target" 2>/dev/null)
    if [ "x$bin_path" != "x" ]; then
        local link="$(dirname $(readlink $bin_path))"
        local dir="$(dirname $bin_path)"
        local pkg_dir="$(basename $(dirname $link))"
        local pkg="${pkg_dir#*-}"

        [ $QUIET -eq 1 ] && echo -e "${pkg}"
        log::ln "Package:     ${cyan}${pkg}${none}"
        log::ln "Link name:   $dir/${cyan}${target}${none}"
        log::ln "Link target: ${link}/${cyan}${target}${none}"
    else
        log::error "Unable to find target: ${cyan}${target}${none}"
    fi
}
