#!/usr/bin/env bash
#set -x

# REPL
# 
# ## Features
# - Setup the local flake for the target host to be used in the REPL
# --------------------------------------------------------------------------------------------------

# Usage for the repl command and its sub commands
# --------------------------------------------------------------------------------------------------
repl::usage()
{
    cat <<USAGE
Usage:
  repl [ARGS...] [OPTIONS] 

Options:
  -h, --help            Print out usage

Arguments:
  HOST                  Load the given host or the default test vm 'vm-test'
USAGE

    log::ln "\nExamples:"
    log::subln "Load host: ${green}./${SCRIPT} repl${none}"
    log::subln "Load given host: ${green}./${SCRIPT} repl macbook${none}"
    echo
    exit
}

# Parse the repl commands and execute
# --------------------------------------------------------------------------------------------------
repl::run()
{
    utils::help "$@" zero "repl::usage"

    # Process the given arguments
    repl::host "$@"
}

# Repl the target host
# - $1 - the host name to target
# --------------------------------------------------------------------------------------------------
repl::host()
{
    core::preamble

    # Use hostname as host
    HOST="$1"
    [[ "$1" == "" ]] && HOST="$(hostname)"
    TARGET="hosts/$HOST"

    log::header1 "Loading ${cyan}${TARGET}${none} in REPL"
    flake::switch "$TARGET"
    trap flake::restore EXIT

    nix repl -f '<nixpkgs>'
}
