#!/usr/bin/env bash

# Usage for the shell command and its sub commands
# --------------------------------------------------------------------------------------------------
shell::usage()
{
    cat <<USAGE
Usage:
  shell [COMMAND] [ARGS...] [OPTIONS]

Options:
  -h, --help            Print out usage
  -p, --packages        Space delimited list of packages to include in the shell

Commands:
  latest [NAME]         Create a shell with access to the latest version of the given app NAME
Commands:
USAGE

    log::ln "\nExamples:"
    log::subln "Shell with wmctrl present: ${green}./${SCRIPT} shell -p wmctrl${none}"
    log::subln "Shell with pyserial present: ${green}./${SCRIPT} shell -p python311Packages.pyserial${none}"
    log::subln "Shell with multiple packages: ${green}./${SCRIPT} shell -p libjpeg openjdk${none}"
    log::subln "Latest given package: ${green}./${SCRIPT} shell latest yt-dlp${none}"
    echo
    exit
}


# Parse the shell commands and execute
# --------------------------------------------------------------------------------------------------
shell::run()
{
    utils::help "$@" "shell::usage"

    # Check if latest command was given
    if [[ "$1" == "latest" ]]; then
        local app="$2"
        log::header1 "Sourcing latest ${cyan}${app}${none}"
        if [[ "$app" != "" ]]; then
          nix-shell -p "(import (fetchTarball \"https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz\") {}).${app}"
        fi
    else
        nix-shell "$@"
    fi
}
