#!/usr/bin/env bash

# Test code
# 
# ## Features
#
# --------------------------------------------------------------------------------------------------

# Parse the test commands and execute
test::run()
{
    core::title
    log::header1 "Test command invoked"
}
