# qBittorrent options
#
#---------------------------------------------------------------------------------------------------
{ config, lib, pkgs, f, ... }: with lib.types;
let
  cfg = config.apps.network.qbittorrent;

  conf = lib.mkIf cfg.enable (pkgs.writeText "qBittorrent.conf" ''
    [LegalNotice]
    Accepted=${f.boolToStr cfg.acceptedLegalNotice}
  '');

  # devilspie2 rule enlarging qBittorrent's file chooser. The chooser is a plain
  # `QFileDialog::getOpenFileNames` static call, so qBittorrent never persists its geometry and there
  # is nothing in `qBittorrent.conf` to set - it comes up at Qt's cramped default size every time.
  # - the dialog already has its final size when the window open event fires, so scaling what is
  #   read back is stable and never compounds across opens
  # - the original centre is kept, then clamped so a large scale can't push it off screen
  fileDialogScript = ''
    -- Generated by modules/apps/network/qbittorrent - do not edit
    if (get_window_class() == "qBittorrent" and get_window_type() == "WINDOW_TYPE_DIALOG"
        and get_window_name() == "Open Torrent Files") then
      local x, y, width, height = get_window_geometry();
      local screenWidth, screenHeight = get_screen_geometry();
      local newWidth = math.min(math.floor(width * ${toString cfg.fileDialogWidthScale}), screenWidth);
      local newHeight = math.min(math.floor(height * ${toString cfg.fileDialogHeightScale}), screenHeight);
      local newX = math.max(0, math.min(x + math.floor((width - newWidth) / 2), screenWidth - newWidth));
      local newY = math.max(0, math.min(y + math.floor((height - newHeight) / 2), screenHeight - newHeight));
      set_adjust_for_decoration(true);
      set_window_geometry(newX, newY, newWidth, newHeight);
    end
  '';
in
{
  options = {
    apps.network.qbittorrent = {
      enable = lib.mkEnableOption "Install and configure qBittorrent";
      acceptedLegalNotice = lib.mkOption {
        type = types.bool;
        default = true;
        description = lib.mdDoc "Accepts the legal notice";
      };
      fileDialogWidthScale = lib.mkOption {
        type = types.float;
        default = 1.5;
        description = lib.mdDoc ''
          Horizontal scale factor applied to the `File -> Open Torrent Files` chooser when it opens,
          keeping it centred. Implemented as a `apps.system.devilspie2` rule, so it has no effect
          unless that option is also enabled. Leave both scales at `1.0` to keep Qt's default size.
        '';
      };
      fileDialogHeightScale = lib.mkOption {
        type = types.float;
        default = 1.75;
        description = lib.mdDoc "Vertical scale factor for the `File -> Open Torrent Files` chooser";
      };
    };
  };

  config = lib.mkIf (cfg.enable) {
    environment.systemPackages = with pkgs; [ qbittorrent ];

    files.all.".config/qBittorrent/qBittorrent.conf".weakCopy = conf;

    apps.system.devilspie2.scripts = lib.mkIf (cfg.fileDialogWidthScale != 1.0 || cfg.fileDialogHeightScale != 1.0) { qbittorrent = fileDialogScript; };
  };
}
