# XFCE Thunar options
#
#---------------------------------------------------------------------------------------------------
{ options, config, lib, pkgs, f, ... }: with lib.types;
let
  xfce = config.system.desktop.xfce;
  cfg = xfce.thunar;

  thunarXmlfile = lib.mkIf xfce.enable
    (pkgs.writeText "thunar.xml" ''
      <?xml version="1.0" encoding="UTF-8"?>
      <channel name="thunar" version="1.0">
        <property name="last-view" type="string" value="${cfg.view}"/>
        <property name="last-show-hidden" type="bool" value="${f.boolToStr cfg.showHidden}"/>
      </channel>
    '');

  thunarVolmanXmlfile = lib.mkIf xfce.enable
    (pkgs.writeText "thunar-volman.xml" ''
      <?xml version="1.0" encoding="UTF-8"?>
      <channel name="thunar-volman" version="1.0">
        <property name="automount-media" type="empty">
          <property name="enabled" type="bool" value="${f.boolToStr cfg.volman.automountMedia}"/>
        </property>
        <property name="automount-drives" type="empty">
          <property name="enabled" type="bool" value="${f.boolToStr cfg.volman.automountDrives}"/>
        </property>
      </channel>
    '');

  # devilspie2 rule placing new Thunar windows on the left half of the screen. Thunar itself only
  # ever persists its window size, never a position, and xfwm4 has no per application placement
  # rules, so the positioning has to come from a window matching daemon.
  # - `maximize_vertically` is used rather than a computed height so the panel struts are honored
  # - dialogs (properties, bulk rename) are excluded by the normal window type check
  snapLeftScript = ''
    -- Generated by modules/system/xfce/thunar.nix - do not edit
    if (get_window_class() == "Thunar" and get_window_type() == "WINDOW_TYPE_NORMAL") then
      local width, height = get_screen_geometry();
      set_adjust_for_decoration(true);
      set_window_geometry(0, 0, math.floor(width / 2), height);
      maximize_vertically();
    end
  '';

in
{
  options = {
    system.desktop.xfce.thunar = {
      view = lib.mkOption {
        type = types.enum [ "ThunarDetailsView" ];
        default = "ThunarDetailsView";
        description = lib.mdDoc "The type of view to use";
      };
      showHidden = lib.mkOption {
        type = types.bool;
        default = true;
        description = lib.mdDoc "Show hidden files and directories";
      };
      snapLeft = lib.mkOption {
        type = types.bool;
        default = true;
        description = lib.mdDoc ''
          Open new Thunar windows snapped to the left half of the screen at full working height.
          Implemented as a `apps.system.devilspie2` rule, so it has no effect unless that option is
          also enabled, and it re-applies to every Thunar window as it opens.
        '';
      };
    };
    system.desktop.xfce.thunar.volman = {
      automountMedia = lib.mkOption {
        type = types.bool;
        default = true;
        description = lib.mdDoc "Mount removable media when inserted";
      };
      automountDrives = lib.mkOption {
        type = types.bool;
        default = true;
        description = lib.mdDoc "Mount removable drives when hot-plugged";
      };
    };
  };

  # Install the generated xml file
  config = lib.mkIf (xfce.enable) {
    programs.thunar.enable = true;            # install and configure thunar
    programs.thunar.plugins = with pkgs; [
      thunar-volman                           # install volman plugin
      thunar-archive-plugin                   # install archive plugin
      thunar-media-tags-plugin                # install media tags plugin
    ];
    services.tumbler.enable = true;           # provides image thumbnails

    files.all.".config/xfce4/xfconf/xfce-perchannel-xml/thunar.xml".weakCopy = thunarXmlfile;
    files.all.".config/xfce4/xfconf/xfce-perchannel-xml/thunar-volman.xml".weakCopy = thunarVolmanXmlfile;

    apps.system.devilspie2.scripts = lib.mkIf (cfg.snapLeft) { thunar = snapLeftScript; };
  };
}
