#!/usr/bin/env bash

# --------------------------------------------------------------------------------------------------
# Clean management commands
# --------------------------------------------------------------------------------------------------
source "${SCRIPT_DIR}/lib/clean/xfce"

# Usage for the clean command and its sub commands
# --------------------------------------------------------------------------------------------------
clean::usage()
{
    cat <<USAGE
Usage:
  clean [OPTIONS] [COMMAND] [ARGS...]

Options:
  -h, --help        Print out usage

Commands:
  all               Clean nix store and generations
  pkg               Clean the given package out of the nix store
  store             Clean the nix store
  vm                Clean the current vm (qcow2, result and store)
  xfce              Clean various xfce components
USAGE

    log::ln "\nExamples:"
    log::subln "Clean nix store only: ${green}./${SCRIPT} clean store${none}"
    log::subln "Clean nix store and generations: ${green}./${SCRIPT} clean all${none}"
    log::subln "Clean nix store package: ${green}./${SCRIPT} clean pkg /nix/store/1234${none}"
    echo
    exit
}


# Parse the clean commands and execute
# --------------------------------------------------------------------------------------------------
clean::run()
{
    utils::help "$@" "clean::usage"

    # Parse the clean commnand
    local command=$1; shift
    case "$command" in
        all) clean::store -d ;;
        pkg) clean::pkg "$@" ;;
        store) clean::store ;;
        vm) clean::vm ;;
        xfce) clean::xfce::run "$@" ;;
        *) log::error "Invalid clean command: ${cyan}${command}${none}"; clean::usage ;;
    esac
}

# Clean the given package from the nix store
# --------------------------------------------------------------------------------------------------
clean::pkg()
{
    nix-store --delete $@
}

# Clean up nix store
# --------------------------------------------------------------------------------------------------
clean::store()
{
    # First clean up all older generations
    [[ $1 == "-d" ]] && nix-collect-garbage -d

    # Now clean the nix store
    nix-store --gc
}

# Clean up the vm
# --------------------------------------------------------------------------------------------------
clean::vm()
{
    # Delete the VM image
    local image="nixos.qcow2"
    if [ -f $image ]; then
        log::ln "Removing VM qcow2 image ${cyan}${image}${none}"
        rm $image
    fi

    # Read the result link for the VM configuration
    if [ -e result ]; then
        local store_path=$(readlink result)

        # Remove the store item
        log::ln "Removing store artifact ${cyan}${store_path}${none}"
        rm result
        nix-store --delete $store_path
    fi
}
