#!/usr/bin/env bash

# --------------------------------------------------------------------------------------------------
# Clean management commands
# --------------------------------------------------------------------------------------------------
source "${SCRIPT_DIR}/lib/clean/xfce"

# Usage for the clean command and its sub commands
# --------------------------------------------------------------------------------------------------
clean::usage()
{
    cat <<USAGE
Usage:
  clean [OPTIONS] [COMMAND] [ARGS...]

Options:
  -h, --help        Print out usage

Commands:
  all               Clean nix store and generations
  pkg               Clean the given package out of the nix store
  store             Clean the nix store
  xfce              Clean various xfce components
USAGE

    log::ln "\nExamples:"
    log::subln "Clean nix store only: ${green}./${SCRIPT} clean store${none}"
    log::subln "Clean nix store and generations: ${green}./${SCRIPT} clean all${none}"
    log::subln "Clean nix store package: ${green}./${SCRIPT} clean pkg /nix/store/1234${none}"
    echo
    exit
}


# Parse the clean commands and execute
# --------------------------------------------------------------------------------------------------
clean::run()
{
    utils::help "$@" "clean::usage"

    # Parse the clean commnand
    local command=$1; shift
    case "$command" in
        all) clean::store -d ;;
        pkg) clean::pkg "$@" ;;
        store) clean::store ;;
        xfce) clean::xfce::run "$@" ;;
        *) log::error "Invalid clean command: ${cyan}${command}${none}"; clean::usage ;;
    esac
}

# Clean the given package from the nix store
# --------------------------------------------------------------------------------------------------
clean::pkg()
{
    nix-store --delete $@
}

# Clean up nix store
# --------------------------------------------------------------------------------------------------
clean::store()
{
    # First clean up all older generations
    [[ $1 == "-d" ]] && nix-collect-garbage -d

    # Now clean the nix store
    nix-store --gc
}
